### ISSUE TITLE
React has no default export

### ISSUE THREAD

**Issue by Tsourdox** [react-ga/react-ga#248] opened 2018-04-27 10:14 UTC
I get an error when using the react-ga library.

> error: node_modules/react-ga/types/index.d.ts:8:8 - react has no default export.

Changing
```
import React from 'react';
```
to
```
import * as React from 'react';
```
solves the issue.

Will this issue be fixed in an upcoming verison?

**Comment by SimeonC** [comment] 2018-04-27 12:59
Duplicate of #246 . Will be fixed next version.

**Closed by SimeonC** 2018-04-27 12:59 UTC
