### ISSUE TITLE
OutboundLink Component not working

### ISSUE THREAD

**Issue by OllieJennings** [react-ga/react-ga#71] opened 2016-05-17 20:34 UTC
So i tried using the `OutboundLink` component, so far all it rendered perfectly, but when l clicked on a link, nothing happened, absolutely nothing happened at all.

**Comment by OllieJennings** [comment] 2016-05-18 08:16
Just from looking through the source code, l guess this bug is due to the fact that the `OutboundLink.trackLink` method does nothing.

```
statics: {
    trackLink: function () {
      console.warn('ga tracking not enabled');
    }
  },
```

I could be wrong here though?

**Comment by OllieJennings** [comment] 2016-05-18 08:20
Okay so it does actually send the tracking event to GA, just checked my analytics now, however it does not open the link in the new tab at all.

**Comment by yangshun** [comment] 2016-05-18 08:21
Can you show us how you are using the component?

**Comment by OllieJennings** [comment] 2016-05-18 08:26
Sure:

```
import { OutboundLink } from 'react-ga';

// The in the code further down
<OutboundLink eventLabel='retailLink' to={url} target='_blank'>{ Title }</OutboundLink>


// Rendering this component would work for testing purposes
<a href={url} target='_blank'>{ Title }</a>
```

This sends the event to Google Analytic's, but it does not open the link in a new Tab, it appears like nothing happens.

**Comment by yangshun** [comment] 2016-05-18 08:53
I don't think we support importing it via that approach. Could you try doing:

```
import ReactGA from 'react-ga';

<ReactGA.OutboundLink eventLabel='retailLink' to={url} target='_blank'>{ Title }</ReactGA.OutboundLink>
```

**Comment by OllieJennings** [comment] 2016-05-18 08:58
@yangshun Sure will do, will get back to you with results

**Comment by OllieJennings** [comment] 2016-05-18 09:19
@yangshun Sadly the results are the exact same :(, the new tab is not opened, nothing happens

**Comment by OllieJennings** [comment] 2016-05-24 11:32
@yangshun may have gotten the answer.

Basically the browsers, namely Safari & Chrome are automatically preventing the link from opening a new tab because they do not allow new windows to be opened inside a function.

Instead new windows can only be opened from within the onClick event itself.

**Comment by yangshun** [comment] 2016-06-11 10:15
Hi @OllieJennings sorry for the slow reply. 

I was never to reproduce the problem of not being able to open the link in a new tab/window. However, I did see any error in the console of `this.send` not being a function due to an incorrect reference to `this.` Have fixed the references issue and hopefully it works for you now. Try updating to 1.5.0 to get the fix.

**Comment by yangshun** [comment] 2016-07-01 17:45
@OllieJennings did you manage to try it?

**Comment by jareddellitt** [comment] 2016-07-27 20:22
I'm also seeing this. Chrome thinks that it's a pop-up and refuses to open the link.

**Comment by OllieJennings** [comment] 2016-08-02 09:38
Hi @yangshun sorry for the very very late reply, just saw this now.

Basically l have realised that you cannot do this in Chrome or Safari due to their security restrictions, the new window can only be opened from within the click event itself.

My work around was to allow the click to open a new tab, whilst the current window sent the event to good in the background, not delaying the click or prevent it from happening.

**Comment by polaski** [comment] 2016-08-03 22:03
Hi, sorry for a newbie question but I am having hard time understanding how this OutboundLink component works in terms of handling clicks. 

Like @OllieJennings mentioned above, the `trackLink` function doensn't seem to do anything other than `console.warn`, but I have a feeling I'm missing something, so after struggling to figure it out on my own, I decided to just ask here, hopefully the answer may help future users as well.

For reference, I have a GA debugger chrome extension running, and while it correctly captures the init event, I don't see any event showing up when I click the OutboundLink component. That's how I started looking into the source. Here's what my OutboundLink looks like:

    1 import React, { Component } from 'react';
    2 import ReactGA from 'react-ga';
    ....
    28   render() {
    29     return <ul className="current-asset">
    30       <li>
    31         <ReactGA.OutboundLink eventLabel='click-edit' to={this.baseURL + this.props.pid} target="_blank">
    32           Edit
    33           <div>{this.status}</div>
    34         </ReactGA.OutboundLink>
    35       </li>
    36       <li>
    37         <ReactGA.OutboundLink eventLabel='click-view' to={this.baseURL + this.props.pid} target="_blank">
    38           View
    39         </ReactGA.OutboundLink>
    40       </li>
    41     </ul>;
    42   }

**Comment by OllieJennings** [comment] 2016-09-23 12:57
@polaski so this won't work, and sorry for responding so late

Basically due to security, you cannot prevent a link from no firing, then open a new tab with the url of the link and focus it. Its just disallowed in the browsers now.

Therefore, you need to make your own function, example below:

```
const sendOutboundEvent = (e) => {
  console.log(e.target.href);
  const link = e.target.href;
  ga.outboundLink({
    label: link
  }, () => {
    console.log('event sent', link);
  });
};
```

Then you do something like:

```
<a href={link} onClick={sendOutboundEvent} target="_blank" > {link tex} </a>
```


So what happens, is the new window is opened, but in the previous one, the event will be sent to GA

**Comment by SimeonC** [comment] 2017-11-04 09:17
I think this should be fixed now. Please re-open if it's not.

**Closed by SimeonC** 2017-11-04 09:17 UTC
