### ISSUE TITLE
Where to view my fieldObject that i sent

### ISSUE THREAD

**Issue by manodupont** [react-ga/react-ga#89] opened 2016-09-15 19:17 UTC
So in my console i can clearly see that something is sent

```
[react-ga] called ga('send', fieldObject);
[react-ga] with fieldObject: {"hitType":"exception","exDescription":"{\"code\":\"avid.upstream/UNAUTHENTICATED\",\"params\":{\"accessToken\":\"YjgwODYzZDgtNTg4ZC00NWE3LTgxOWUtODRiNDEwZDI0YWU2\"},\"message\":\"Access Token Is Invalid\",\"incident\":\"69976400-7b78-11e6-9225-128f9da85adb\",\"exchange\":\"69956830-7b78-11e6-9225-128f9da85adb\",\"status\":401}","exFatal":true}
```

But i can't find those on my Google Account. I only see the pageview /index.html that i set before. But where can I see those hitType object for example ?

**Comment by yangshun** [comment] 2016-10-08 05:30
Duplicate of #90

**Closed by yangshun** 2016-10-08 05:30 UTC
Labels: hacktoberfest
